### ISSUE TITLE
ReaderWriterLockSlim

### ISSUE THREAD

**Issue by ericlaw1979** [vcsjones/FiddlerCertGen#2]
Since you're targeting .NET4, does it make sense to use `ReaderWriterLockSlim` instead of the older class? From MSDN:

> ReaderWriterLockSlim is similar to ReaderWriterLock, but it has simplified rules for recursion and for upgrading and downgrading lock state. ReaderWriterLockSlimavoids many cases of potential deadlock. In addition, the performance of ReaderWriterLockSlim is significantly better than ReaderWriterLock. ReaderWriterLockSlim is recommended for all new development.

**Comment by vcsjones** [comment]
I used `ReaderWriterLock` so that while yes, it does target .NET Framework 4, you can change it to 2.0 and it will still compile with no code modifications. In fact I would probably use `ConcurrentDictionary` and try and get rid of the reader-writer lock all together.

I intended to make a 2.0 and a 4.0 version of it, but left the code as "Targets 4.0 but should work on 2.0" for now.

**Comment by ericlaw1979** [comment]
Ah, interesting. thanks.

**Comment by vcsjones** [comment]
I decided to use more modern mechanisms for the 4.0 project. The 2.0 is in history, and I'll eventually get around to writing a separate project for it.
